# Configure the AWS cluster

# Set region
# see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions
region: eu-west-2

# Set cluster name
cluster_name: the_new_cluster

# Set subnets
private_subnets:
    # Subnet 1
    - 10.0.0.0/19
    - us-east-1a
    # Subnet 2
    - 10.0.32.0/19
    - us-east-1b
    # Subnet 3
    - 10.0.64.0/19
    - us-east-1a
    # Subnet 4
    - 10.0.96.0/19
    - us-east-1b

# Set namespaces
namespaces:
    - my-namespace

# Configure ingress
ingress_HTTPS:
    from_port: 443
    to_port: 443
    protocol: tcp

ingress_HTTP:
    from_port: 80
    to_port: 80
    protocol: tcp
    
ingress_custom:
    from_port: 8080
    to_port: 8080
    protocol: tcp

# Set node group capacity
capacity:
    desired_size: 2
    min_size: 1
    max_size: 3
    instance_types:
    # see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html
        - t2.small
    # see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-purchasing-options.html
    capacity_type: ON_DEMAND