# Configure the AWS cluster

region: us-east-1

cluster_name: my_eks

# Subnets
private_subnets:
    - 10.0.0.0/19
    - 10.0.32.0/19

# Namespaces
# This needs changed - unsure of what namespaces will be used
namespaces:
    - default

# Ingress
# Currently unsure what ingress variables we're changing
ingress:
    from_port: 22
    to_port: 22
    protocol: tcp
    cidr_blocks: # Subnet node group runs in
        - 10.0.0.0/8

# Capacity
capacity:
    desired_size: 1
    min_size: 1
    max_size: 2
    instance_types: 
        - t3.micro
    capacity_type: SPOT