name: Terraform Workflow

 
on:
  push:
    branches: 
      - pipeline-test-2
env:
  TF_WORKSPACE: "AC41004-project"
  CONFIG_DIRECTORY: "./"
  AWS_ACCESS_KEY_ID: ASIA5KSRLFHIJDGQLXGL
  AWS_SECRET_ACCESS_KEY: mpmBH48tBt/xTcMO9zX523FjhlqqF6X0bCmLxx1P
  REGION: us-east-1
jobs:
    runs-on: ubuntu-latest
    name: initialise
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 
    - name: Initialize Terraform
      run: terraform init
    - name: Validate
      run: terraform validate
    - name: plan
      run: terraform plan -destroy
    - name: apply
      run: terraform apply --auto-approve