
name: Terraform Workflow


on:
  push:
    branches:
      - pipeline-test-2
permissions:
      id-token: write
      contents: read
env:
  TF_WORKSPACE: "AC41004-project"
  CONFIG_DIRECTORY: "./"
  AWS_ACCESS_KEY_ID: ASIA5KSRLFHIJDGQLXGL
  AWS_SECRET_ACCESS_KEY: mpmBH48tBt/xTcMO9zX523FjhlqqF6X0bCmLxx1P
  REGION: us-east-1
  # CLUSTER_NAME: industrial-cluster-5
jobs:
  # configure_AWS:
  #   runs-on: ubuntu-latest 
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Configure AWS Credentials
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       aws-access-key-id: ASIA5KSRLFHIH257HUME
  #       aws-secret-access-key: fV8wSk8uwvTiCzOpcBJTMU/WOkzwhhg2zhr20fob
  #       aws-region: us-east-1
  #       aws-session-token: IQoJb3JpZ2luX2VjEGgaCXVzLWVhc3QtMSJHMEUCIEYqbmAvpK3TNqdCQ0FFPjqRsTyTn1a0n/9InsC0sjzDAiEAhvJHdupIbjF1HiYMV4K/nQ7scgOt9ATpNWWHgMGA3Vcq5gIIYBAAGgw5MTYwNzIzNzY3ODQiDLbPXiCHhi4nR6MPEirDAqObA89nQEYJI20t6HCkLJVE0+gRj0zTRc43rsaZ8cc8UWAmp5MORm7s42eCh1FVOiC4Ze4+Ja2TdGfQrhmX1ITUZDrk+fLFuGwMYY0gYHy1m94ff0+V/Uv93k2EfVR83gJm0b/VP/8OOimDKPbAr9pBmaa6iJSosOBXyWjeuYabKLCIVtOdC745CWY+qX/dwuDNAHHSggb48aGUSifAwWtwka1nNfme0M4PDhT2XJ29KKPxHwQ/682awhPlJGfTXsKAuF37r/BAit2LpN262x9Oa7rhfTnjFBEALKy6IBolx62QT4ZS3fLr6Nah+OFJuIxv35SWaZQvn9tRsVMkMKwf8mOpQt7C7MhoLUeN64PJSDXW9EZ8Gl9T5ezxYk43TjAZcCqCrxcwgmmvPfnLkhvlXmhFEjuap5D7gUR1vYrFD6nuMITGxqgGOqcBtds5HgoSZEm3W9UMOTILwvlgEq2Kq4yh2t9/VeRIPGlFxwwZlb58AP0Iv09OUTLEWKbxlwf27jtSPB78Ji7oSJhcxjhWlFxkNLpFrUspKTLb7gB8Ap4jwbYvdNhlry4pav0rUJqi6nqrGKdmI7XZkThd9K7bzY7/wxK5ldn4djcISgpSOKl6hSFS6Azak0RfQvn6i+htaYb5KOV58OuezUk6aUBeBIQ=
  #       role-to-assume: arn:aws:iam::123456789100:role/my-other-github-actions-role
  #       # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
  #       # role-duration-seconds: 1200
  #       # role-session-name: MySessionName
  initialise:
    # needs: configure_AWS
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 
    - name: Initialize Terraform
      run: terraform init
    - name: Validate
      run: terraform validate
    - name: plan
      run: terraform plan -destroy
    - name: apply
      run: SET AWS_ACCESS_KEY_ID=ASIA5KSRLFHIJDGQLXGL
      run: SET AWS_SECRET_ACCESS_KEY=mpmBH48tBt/xTcMO9zX523FjhlqqF6X0bCmLxx1P
      run: SET AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEHoaCXVzLWVhc3QtMSJHMEUCIDgGC43dCTsE7Rn9CIuIPMcX7zguH/C1WVgsZpvvi9sJAiEAsECBJG4dFkzq0puWxxNQZBwn1cO6FS7guApAb+m7qfsq6gIIchAAGgw5MTYwNzIzNzY3ODQiDPsupaZLLdO3Jy5t/irHAvNDucHR7/OAaRP4LXd4CAJm4KULUImBA1ePudy5u3egyie4YflU+GEGnVXc6yd31XV/DWG9EU+9J12NcTfxmwellB1vPfchwxvJixWNgW6AM0KUcqgMF2SwS0xANIW52pjz7u+AamoEK9NqlJvw/mNWIB9hz8yf+s9mHMsPLSnAKx2jXNa7q7UtjYwbm9Ze3WR1j/Daq3USQkO4UTXGyQ21bxeBUUpH0Qp9qI/t/cpoVWh1qKPSckWgNlEtyvtVnA4w8hgS/luaAEuiXblVAsRT6toUoJ9ACXMTYLL4qXoUyeYd1BZ2XCgGtV/4DUEk72PHc0E4kwt5mxpPlc64j7M71plNIgFxfY3WbFArpXq/OQVCzyHDkXE9GsUm0jOpXxz589DDE6q6iSbK72sXVLw8c1MUlS3a7V6QiRB4AHnv8drY7Qn/TDCPxMqoBjqnAXhGXVZ7OR0U7224912+ryINWOgq9Sng8So9RxL2La1Q7BItcnpa/3sAY2EFs71H9YKOfC3ZQzBqwvaXQVBUHEMm3d9tjr8HxjMTJcvIQquGweCnZw5x5J1EMJZvKPQh34bVAsO92GfHWRy4BYpSnEkNtOb0h9Gx+86WM6btCkNADXr1NOqH6PRm3L4aqlut4Cu69GqPHsSUo20VSMoNUo/KY2ajlx8j
      run: aws sts get-caller-identity
  # apply_changes:
  #   needs: validate
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Create New File
  #       run: |
  #         echo "This is a new file." > newfile2.txt
  #         git config --global user.name "ZenLuca170018137"
  #         git config --global user.email "lzen@dundee.ac.uk"
  #         git add newfile2.txt
  #         git commit -m "Add newfile.txt"
  #         git push origin main
  #     - name: Append to the file
  #       run: |
  #         echo "Append test." >> newfile2.txt
  #         git config --global user.name "ZenLuca170018137"
  #         git config --global user.email "lzen@dundee.ac.uk"
  #         git add newfile2.txt
  #         git commit -m "Append newfile.txt"
  #         git push origin main
  #     - name: Search File
  #       run: |
  #         search_term="Append"
  #         file_to_search="newfile2.txt"

  #         if grep -q "$search_term" "$file_to_search"; then
  #           echo "Term existing." >> newfile2.txt
  #           git config --global user.name "ZenLuca170018137"
  #           git config --global user.email "lzen@dundee.ac.uk"
  #           git add newfile2.txt
  #           git commit -m "search positive.txt"
  #           git push origin main
  #         else
  #           echo "Term not existing." >> newfile2.txt
  #           git config --global user.name "ZenLuca170018137"
  #           git config --global user.email "lzen@dundee.ac.uk"
  #           git add newfile2.txt
  #           git commit -m "search negative.txt"
  #           git push origin main
  #         fi
  #     - name: Extract Word
  #       id: extract-word
  #       run: | 
  #           # Specify the file name to read from
  #           file_to_read="newfile2.txt"
  #           # Specify the line number containing the word (adjust as needed)
  #           line_number=2
  #           # Use awk to extract the word from the specified line
  #           extracted_word=$(awk "NR==$line_number{print \$2}" "$file_to_read")
  #           echo "::set-output name=extracted_word::$extracted_word"

  #     - name: Use Extracted Word
  #       run: |
  #           extracted_word="${{ steps.extract-word.outputs.extracted_word }}"
  #           echo "Extracted Word: $extracted_word"